services:
  app_back_service:
    container_name: "beautyhub_back"

    build: .
    depends_on:
      app_db_service:
        condition: service_healthy
    
    ports:
      - 7777:8000
    networks:
      - appNetwork
    env_file:
      - .envdocker
      
  app_db_service:
    container_name: "beautyhub_db"
    image: postgres:17.6
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: abcde1234
      POSTGRES_DB: beautyhub
    ports:
      - 7432:5432
    networks:
      - appNetwork
    volumes:
      - pg-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 2s
      timeout: 5s
      retries: 10
    env_file:
      - .envdocker

networks:
  appNetwork:
    driver: bridge

volumes:
  pg-data:
    driver: local
