services:
  app_db_service:
    container_name: "beautyhub_db"
    image: postgres:17.6
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: abcde1234
      POSTGRES_DB: beautyhub
    ports:
      - 7432:5432
    networks:
      - appNetwork
    volumes:
      - pg-data:/var/lib/postgresql/data
    env_file:
      - .envdocker

networks:
  appNetwork:
    driver: bridge

volumes:
  pg-data:
    driver: local
